### Test requests for Web3j Open API PoC 

GET http://localhost:8080/api/contracts

###

POST http://localhost:8080/api/contracts/Greeter
Content-Type: application/json

{
  "greeting": "Hello world!"
}

###

GET http://localhost:8080/api/contracts/Greeter/0x1cce642fdc36db4fe5680c310a9d7fb1e11a4d25/greet

###

POST http://localhost:8080/api/contracts/Greeter/0x1cce642fdc36db4fe5680c310a9d7fb1e11a4d25/newGreeting
Content-Type: application/json

{
  "greeting": "Hello new world!"
}

###
