# To build a Dockerized version execute: `docker build -t <projectRootDirectory> .`
FROM adoptopenjdk/openjdk11
RUN mkdir /opt/app
COPY . /opt/app
WORKDIR /opt/app
RUN ./gradlew installDist
ENTRYPOINT ["./server/build/install/{{projectName}}/bin/{{projectName}}-server", "run"]