# To build a Dockerized version execute: `docker build -t <projectRootDirectory> .`
FROM adoptopenjdk/openjdk11
RUN mkdir /opt/app
COPY . /opt/app
WORKDIR /opt/app
RUN curl -L get.epirus.io | sh
ENTRYPOINT ["/root/.epirus/epirus", "run", "rinkeby"]